polySphere -radius 2 -name "head";
polyCone -radius 1 -name "nose";

move 2.5 0 0;
rotate 0 0 -90;

polySphere -radius 0.3 -name "rEye";
move 1.5 1 0.7;
polySphere -radius 0.3 -name "lEye";
move 1.5 1 -0.7;
polyCube -d 0.6 -h 0.2 -w 0.2 -name "lEyebrow";
move 1.2 1.5 -0.8;
rotate -30 0 0;
polyCube -d 0.6 -h 0.2 -w 0.2 -name "rEyebrow";
move 1.2 1.5 0.8;
rotate 30 0 0;
select -all; //Markerar allt
group - name "HeadGRP";


